name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Initialize Git User
      run: |
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_NAME }}"
    - name: Building Website
      run: |
        yarn
        yarn build
    - name: Clone destination repositories
      run: |
        git clone https://${{ secrets.GIT_USER }}:${{ secrets.GIT_TOKEN }}@github.com/siarie/siarie.github.io
        ls -al siarie.github.io
    - name: Clean destination directory
      run: |
        find siarie.github.io | grep -v ^siarie.github.io/\.git | grep -v ^siarie.github.io | xargs rm -rf
        ls -al siarie.github.io
    - name: Copy content to git repo
      run: |
        cp -r dist/* siarie.github.io
    - name: Deploying website
      run: |
        cd siarie.github.io
        ls -la
        git add .
        git status
        git commit -m "Last update $(TZ='Asia/Jakarta' date)"
        git push
